### PR TITLE
added new colors

### PR DESCRIPTION
**Pull request by Speedy0197**
added the 12 colors from theOtherRoles

### CODE REVIEW

**Comment by CarbonNeuron** [comment]
This wont work without the changing of server code.

**Comment by CarbonNeuron** [comment]
#194 was denied.

**Comment by Frozen-byte** [comment]
would resolve https://github.com/automuteus/amonguscapture/issues/194

Server-Changes: https://github.com/denverquane/automuteus/pull/424

**Comment by CarbonNeuron** [comment]
But @denverquane denied the issue that pr was referencing

**Comment by Frozen-byte** [comment]
Please have a look at the latest Update from the Devs. More Players are planned anyways. I guess the same Changes are required for Vanilla-15-Player-Lobbies.

Since the Code was already written for 10+ Players I guess it's Code that is required in the near future.

Still the Quota-Problems and everything else @denverquane stated out remains untouched.

**Pull request closed without merging**
